name: Receive Config Update with Proxy

on:
  repository_dispatch: # Nhận request từ Config.html qua webhook
    types: [update-config-proxy]

jobs:
  proxy-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Receive and Validate Payload
        run: |
          echo "Payload received: ${{ toJSON(github.event.client_payload) }}" > payload.json
          SECRET_KEY="${{ secrets.CONFIG_SECRET_KEY }}"
          if [ "${{ github.event.client_payload.secret_key }}" != "$SECRET_KEY" ]; then
            echo "❌ Secret key không hợp lệ"
            exit 1
          fi
          echo "✅ Secret key hợp lệ"

      - name: Trigger Update Config Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # Cập nhật khớp với secret name
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{
              "event_type": "update-config",
              "client_payload": {
                "minRate": ${{ github.event.client_payload.minRate }},
                "minBox": ${{ github.event.client_payload.minBox }},
                "smallBoxThreshold": ${{ github.event.client_payload.smallBoxThreshold }},
                "priorityContinents": ${{ github.event.client_payload.priorityContinents }},
                "specificCountries": ${{ github.event.client_payload.specificCountries }}
              }
            }'
          echo "✅ Đã gửi repository_dispatch để cập nhật 1Config.json"
