name: Receive Config Update

on:
  workflow_dispatch: # Cho phép gọi từ Config.html
    inputs:
      secret_key: # Secret key để xác thực
      minRate:
      minBox:
      smallBoxThreshold:
      priorityContinents:
      specificCountries:

jobs:
  receive-config:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Secret Key
        run: |
          if [ "${{ inputs.secret_key }}" != "${{ secrets.CONFIG_SECRET_KEY }}" ]; then
            echo "❌ Secret key không hợp lệ"
            exit 1
          fi
          echo "✅ Secret key hợp lệ"

      - name: Trigger Update Config Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # PAT lưu trong Secrets
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{
              "event_type": "update-config",
              "client_payload": {
                "minRate": ${{ inputs.minRate }},
                "minBox": ${{ inputs.minBox }},
                "smallBoxThreshold": ${{ inputs.smallBoxThreshold }},
                "priorityContinents": ${{ inputs.priorityContinents }},
                "specificCountries": ${{ inputs.specificCountries }}
              }
            }'
          echo "✅ Đã gửi repository_dispatch để cập nhật 1Config.json"
