name: Receive Config Update with Proxy

on:
  repository_dispatch: # Nhận request công khai
    types: [update-config-proxy]

jobs:
  proxy-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Internal Secret
        run: |
          # Kiểm tra secret nội bộ, không cần từ client
          if [ -z "${{ secrets.INTERNAL_SECRET }}" ]; then
            echo "❌ INTERNAL_SECRET không được định nghĩa"
            exit 1
          fi
          echo "✅ Internal secret hợp lệ"

      - name: Trigger Update Config Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{
              "event_type": "update-config",
              "client_payload": {
                "minRate": ${{ github.event.client_payload.minRate }},
                "minBox": ${{ github.event.client_payload.minBox }},
                "smallBoxThreshold": ${{ github.event.client_payload.smallBoxThreshold }},
                "normalMinBox": ${{ github.event.client.payload.normalMinBox }},
                "normalMinRate": ${{ github.event.client.payload.normalMinRate }},
                "normalSmallBoxThreshold": ${{ github.event.client.payload.normalSmallBoxThreshold }},
                "potentialMinBox": ${{ github.event.client.payload.potentialMinBox }},
                "potentialMinRate": ${{ github.event.client.payload.potentialMinRate }},
                "potentialSmallBoxThreshold": ${{ github.event.client.payload.potentialSmallBoxThreshold }},
                "priorityContinents": ${{ github.event.client_payload.priorityContinents }},
                "specificCountries": ${{ github.event.client_payload.specificCountries }},
                "idolIds": ${{ github.event.client_payload.idolIds }}
              }
            }'
          echo "✅ Đã gửi repository_dispatch để cập nhật 1Config.json"
