name: Receive Config Update with Proxy

on:
  workflow_dispatch: # Thay bằng workflow_dispatch, an toàn hơn
    inputs:
      secret_key: # Yêu cầu secret key để xác thực
      minRate:
      minBox:
      smallBoxThreshold:
      priorityContinents:
      specificCountries:

jobs:
  proxy-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Receive and Validate Payload
        run: |
          echo "Payload received: ${{ toJSON(github.event.inputs) }}" > payload.json
          SECRET_KEY="${{ secrets.CONFIG_SECRET_KEY }}"
          if [ "${{ github.event.inputs.secret_key }}" != "$SECRET_KEY" ]; then
            echo "❌ Secret key không hợp lệ"
            exit 1
          fi
          echo "✅ Secret key hợp lệ"

      - name: Trigger Update Config Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{
              "event_type": "update-config",
              "client_payload": {
                "minRate": ${{ github.event.inputs.minRate }},
                "minBox": ${{ github.event.inputs.minBox }},
                "smallBoxThreshold": ${{ github.event.inputs.smallBoxThreshold }},
                "priorityContinents": ${{ github.event.inputs.priorityContinents }},
                "specificCountries": ${{ github.event.inputs.specificCountries }}
              }
            }'
          echo "✅ Đã gửi repository_dispatch để cập nhật 1Config.json"
