name: Receive Config Update with Proxy

on:
  workflow_dispatch:
    inputs:
      minRate:
      minBox:
      smallBoxThreshold:
      normalMinBox:
      normalMinRate:
      normalSmallBoxThreshold:
      potentialMinBox:
      potentialMinRate:
      potentialSmallBoxThreshold:
      priorityContinents:
      specificCountries:
      idolIds:

jobs:
  proxy-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Internal Secret
        run: |
          echo "Payload received: ${{ toJSON(github.event.inputs) }}" > payload.json
          INTERNAL_SECRET="${{ secrets.INTERNAL_SECRET }}"
          if [ "$INTERNAL_SECRET" != "jimmyhoang777" ]; then
            echo "❌ INTERNAL_SECRET không hợp lệ"
            exit 1
          fi
          echo "✅ Internal secret hợp lệ"

      - name: Trigger Update Config Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{
              "event_type": "update-config",
              "client_payload": {
                "minRate": ${{ github.event.inputs.minRate }},
                "minBox": ${{ github.event.inputs.minBox }},
                "smallBoxThreshold": ${{ github.event.inputs.smallBoxThreshold }},
                "normalMinBox": ${{ github.event.inputs.normalMinBox }},
                "normalMinRate": ${{ github.event.inputs.normalMinRate }},
                "normalSmallBoxThreshold": ${{ github.event.inputs.normalSmallBoxThreshold }},
                "potentialMinBox": ${{ github.event.inputs.potentialMinBox }},
                "potentialMinRate": ${{ github.event.inputs.potentialMinRate }},
                "potentialSmallBoxThreshold": ${{ github.event.inputs.potentialSmallBoxThreshold }},
                "priorityContinents": ${{ github.event.inputs.priorityContinents }},
                "specificCountries": ${{ github.event.inputs.specificCountries }},
                "idolIds": ${{ github.event.inputs.idolIds }}
              }
            }'
          echo "✅ Đã gửi repository_dispatch để cập nhật 1Config.json"
